"""Validation report generation for publications.

This module generates publication-ready validation reports including:
- LaTeX tables for paper inclusion
- JSON summaries for data analysis
- Console-formatted summaries

Designed for Applied Energy, IEEE Transactions, and similar journals.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import List, Dict, Any

from energis.validation.analytical_benchmarks import ValidationResult, ValidationSuiteResult


def generate_validation_report(
    suite_result: ValidationSuiteResult,
    output_dir: str,
    include_latex: bool = True,
    include_json: bool = True,
    include_csv: bool = True,
) -> Dict[str, str]:
    """Generate comprehensive validation report.

    Parameters
    ----------
    suite_result : ValidationSuiteResult
        Results from run_validation_suite()
    output_dir : str
        Output directory for report files
    include_latex : bool
        Generate LaTeX table
    include_json : bool
        Generate JSON summary
    include_csv : bool
        Generate CSV data file

    Returns
    -------
    Dict[str, str]
        Mapping of report type to file path
    """
    os.makedirs(output_dir, exist_ok=True)
    generated_files = {}

    if include_latex:
        latex_path = os.path.join(output_dir, "validation_results.tex")
        _generate_latex_table(suite_result, latex_path)
        generated_files["latex"] = latex_path

    if include_json:
        json_path = os.path.join(output_dir, "validation_results.json")
        _generate_json_report(suite_result, json_path)
        generated_files["json"] = json_path

    if include_csv:
        csv_path = os.path.join(output_dir, "validation_results.csv")
        _generate_csv_report(suite_result, csv_path)
        generated_files["csv"] = csv_path

    # Generate summary text file
    summary_path = os.path.join(output_dir, "validation_summary.txt")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(suite_result.summary())
    generated_files["summary"] = summary_path

    return generated_files


def _generate_latex_table(
    suite_result: ValidationSuiteResult,
    output_path: str,
) -> None:
    """Generate LaTeX table for publication."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("% Analytical Validation Results\n")
        f.write("% Generated by EnerGIS Framework\n")
        f.write("% Timestamp: " + datetime.now().isoformat() + "\n\n")

        f.write("\\usepackage{booktabs}\n")
        f.write("\\usepackage{xcolor}\n\n")

        f.write("\\begin{table}[htbp]\n")
        f.write("\\centering\n")
        f.write("\\caption{Analytical Validation Benchmark Results}\n")
        f.write("\\label{tab:validation_results}\n")
        f.write("\\begin{tabular}{lrrrc}\n")
        f.write("\\toprule\n")
        f.write("Test Case & Expected & Actual & Rel. Error [\\%] & Status \\\\\n")
        f.write("\\midrule\n")

        for result in suite_result.results:
            # Shorten test name for display
            test_name = result.test_name.replace("_", " ")
            if len(test_name) > 30:
                test_name = test_name[:27] + "..."

            # Format values
            expected_str = f"{result.expected:.4g}"
            actual_str = f"{result.actual:.4g}"
            error_str = f"{result.relative_error * 100:.2f}"

            # Status with color
            if result.passed:
                status = "\\textcolor{green!60!black}{\\checkmark}"
            else:
                status = "\\textcolor{red}{\\texttimes}"

            f.write(f"{test_name} & {expected_str} & {actual_str} & {error_str} & {status} \\\\\n")

        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")

        # Add summary
        f.write(f"\\\\[0.5em]\n")
        f.write(f"\\footnotesize{{Pass rate: {suite_result.pass_rate:.1f}\\% ")
        f.write(f"({suite_result.passed_tests}/{suite_result.total_tests} tests). ")
        f.write(f"Tolerance: 1\\% relative error.}}\n")

        f.write("\\end{table}\n")


def _generate_json_report(
    suite_result: ValidationSuiteResult,
    output_path: str,
) -> None:
    """Generate JSON report for data analysis."""
    report = {
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "framework_version": "2.0",
            "total_tests": suite_result.total_tests,
            "passed_tests": suite_result.passed_tests,
            "failed_tests": suite_result.failed_tests,
            "pass_rate_percent": suite_result.pass_rate,
        },
        "results": [result.to_dict() for result in suite_result.results],
        "summary_by_category": _summarize_by_category(suite_result),
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)


def _generate_csv_report(
    suite_result: ValidationSuiteResult,
    output_path: str,
) -> None:
    """Generate CSV report for spreadsheet analysis."""
    import csv

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter=";")

        # Header
        writer.writerow([
            "Test Name",
            "Passed",
            "Expected",
            "Actual",
            "Relative Error",
            "Absolute Error",
            "Category",
            "Tolerance",
        ])

        # Data rows
        for result in suite_result.results:
            writer.writerow([
                result.test_name,
                result.passed,
                result.expected,
                result.actual,
                result.relative_error,
                result.absolute_error,
                result.details.get("category", ""),
                result.details.get("tolerance", ""),
            ])


def _summarize_by_category(
    suite_result: ValidationSuiteResult,
) -> Dict[str, Dict[str, Any]]:
    """Summarize results by test category."""
    categories: Dict[str, List[ValidationResult]] = {}

    for result in suite_result.results:
        category = result.details.get("category", "general")
        if category not in categories:
            categories[category] = []
        categories[category].append(result)

    summary = {}
    for category, results in categories.items():
        passed = sum(1 for r in results if r.passed)
        total = len(results)
        summary[category] = {
            "total_tests": total,
            "passed_tests": passed,
            "failed_tests": total - passed,
            "pass_rate_percent": (passed / total * 100) if total > 0 else 0,
        }

    return summary


def export_validation_summary(
    suite_result: ValidationSuiteResult,
) -> str:
    """Export validation summary as formatted string.

    Suitable for console output or log files.

    Parameters
    ----------
    suite_result : ValidationSuiteResult
        Results from validation suite

    Returns
    -------
    str
        Formatted summary string
    """
    return suite_result.summary()


def format_for_publication(
    suite_result: ValidationSuiteResult,
    journal_style: str = "applied_energy",
) -> str:
    """Format validation results for specific journal style.

    Parameters
    ----------
    suite_result : ValidationSuiteResult
        Results from validation suite
    journal_style : str
        Target journal: "applied_energy", "ieee", "energy"

    Returns
    -------
    str
        Journal-formatted text suitable for methods section
    """
    lines = []

    if journal_style == "applied_energy":
        lines.append("The optimization framework was validated using a suite of")
        lines.append(f"analytical benchmark tests. A total of {suite_result.total_tests}")
        lines.append("test cases were executed, covering energy balance verification,")
        lines.append("heat pump COP calculations, storage round-trip efficiency,")
        lines.append("and merit order dispatch logic.")
        lines.append("")
        lines.append(f"The validation achieved a pass rate of {suite_result.pass_rate:.1f}%")
        lines.append(f"({suite_result.passed_tests}/{suite_result.total_tests} tests)")
        lines.append("with a tolerance of 1% relative error.")

    elif journal_style == "ieee":
        lines.append("Validation Results:")
        lines.append(f"- Total tests: {suite_result.total_tests}")
        lines.append(f"- Passed: {suite_result.passed_tests}")
        lines.append(f"- Failed: {suite_result.failed_tests}")
        lines.append(f"- Pass rate: {suite_result.pass_rate:.1f}%")

    else:
        lines.append(suite_result.summary())

    return "\n".join(lines)
