"""Generate only the polished Applied Energy figure set requested for review."""
from __future__ import annotations

import importlib
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from scripts.paper.figures.fig_utils import FIG_DIR, FIG_FORMATS


FIGURE_SCRIPTS = [
    {
        "module": "scripts.paper.figures.fig_validation_scatter_tsup",
        "stem": "F_validation_scatter_tsup",
        "inputs": ["tools.validation_runner.DATA_PATH", "tools.validation_runner.PIPE_CATALOG"],
    },
    {
        "module": "scripts.paper.figures.fig_effect_hierarchy_combined",
        "stem": "F_effect_hierarchy_combined",
        "inputs": ["hardcoded paper values in script"],
    },
    {
        "module": "scripts.paper.figures.fig_pareto_accuracy_vs_solvetime",
        "stem": "F_pareto_accuracy_vs_solvetime",
        "inputs": ["hardcoded paper values in script"],
    },
    {
        "module": "scripts.paper.figures.fig_synth_sweep_combined",
        "stem": "F10_synth_sweep_combined",
        "inputs": [
            "output/paper_runs/synth_sweep_results.csv",
            "output/paper_runs/synth_large_scale_results.csv (optional)",
        ],
    },
    {
        "module": "scripts.paper.figures.fig_synth_gap_distribution",
        "stem": "fig_synth_gap_distribution",
        "inputs": ["output/paper_runs/synth_gap_summary.csv"],
    },
    {
        "module": "scripts.paper.figures.fig_synth_gap_direction",
        "stem": "fig_synth_gap_direction",
        "inputs": ["output/paper_runs/synth_gap_summary.csv"],
    },
    {
        "module": "scripts.paper.figures.fig_synth_gap_decomp",
        "stem": "fig_synth_gap_decomp",
        "inputs": ["output/paper_runs/synth/*/economics.csv"],
    },
    {
        "module": "scripts.paper.figures.fig_demand_per_node",
        "stem": "fig_demand_per_node",
        "inputs": [
            "output/paper_runs/L3/nodes_summary.csv",
            "output/paper_runs/L2/nodes_summary.csv",
        ],
    },
    {
        "module": "scripts.paper.figures.fig_cost_extended",
        "stem": "fig_cost_extended",
        "inputs": [
            "output/paper_runs/L3/economics.csv",
            "output/paper_runs/L3plus/economics.csv",
            "output/paper_runs/L3NL/economics.csv",
        ],
        "required_paths": [
            "output/paper_runs/L3/economics.csv",
            "output/paper_runs/L3plus/economics.csv",
            "output/paper_runs/L3NL/economics.csv",
        ],
    },
    {
        "module": "scripts.paper.figures.fig_cost_topology",
        "stem": "fig_cost_topology",
        "inputs": [
            "output/paper_runs/L1/economics.csv",
            "output/paper_runs/L2/economics.csv",
            "output/paper_runs/L3/economics.csv",
        ],
    },
    {
        "module": "scripts.paper.figures.fig_cost_waterfall",
        "stem": "fig_cost_waterfall",
        "inputs": [
            "output/paper_runs/L3/economics.csv",
            "output/paper_runs/L3plus/economics.csv",
        ],
    },
    {
        "module": "scripts.paper.figures.fig_dispatch_heatmap",
        "stem": "fig_dispatch_heatmap",
        "inputs": ["output/paper_runs/L3plus/dispatch_hourly.csv"],
    },
]


def _fresh_outputs(stem: str, started_at: float) -> list[Path]:
    paths: list[Path] = []
    for fmt in FIG_FORMATS:
        path = FIG_DIR / f"{stem}.{fmt}"
        if path.exists() and path.stat().st_mtime >= started_at:
            paths.append(path)
    return paths


def _missing_required_paths(spec: dict[str, object]) -> list[str]:
    missing: list[str] = []
    for raw in spec.get("required_paths", []):
        path = ROOT / str(raw)
        if not path.exists():
            missing.append(str(raw))
    return missing


def _write_report(results: list[dict[str, object]]) -> None:
    report = FIG_DIR / "figure_polish_report.md"
    lines = [
        "# Figure polish report",
        "",
        "## Scope confirmations",
        "- Only the 12 requested existing Matplotlib figure scripts were run.",
        "- No new figure concepts were created.",
        "- Figure 1 and Figure 2 were not regenerated by this runner.",
        "- PowerPoint-based figures, solver runs, model calculations, paper text, and data sources were not touched by this runner.",
        "- Placeholder and fake-data export paths were disabled in the polished scripts.",
        "",
        "## Export settings",
        f"- Output directory: `{FIG_DIR.relative_to(ROOT)}`",
        f"- Formats: {', '.join(FIG_FORMATS)}",
        "- Raster DPI: 900",
        "",
        "## Figures",
    ]

    for result in results:
        lines.append("")
        lines.append(f"### {result['stem']}")
        lines.append(f"- Script: `{result['module']}`")
        lines.append(f"- Status: {result['status']}")
        lines.append(f"- Inputs: {', '.join(f'`{i}`' for i in result['inputs'])}")
        if result["outputs"]:
            outs = ", ".join(f"`{Path(o).name}`" for o in result["outputs"])
            lines.append(f"- Exported: {outs}")
        if result["message"]:
            lines.append(f"- Note: {result['message']}")

    skipped = [r for r in results if r["status"] != "exported"]
    lines.append("")
    lines.append("## Skipped figures")
    if skipped:
        for result in skipped:
            lines.append(f"- `{result['stem']}`: {result['message'] or result['status']}")
    else:
        lines.append("- None.")

    lines.append("")
    lines.append("## Changed files")
    changed_files = [
        "scripts/paper/figures/fig_validation_scatter_tsup.py",
        "scripts/paper/figures/fig_effect_hierarchy_combined.py",
        "scripts/paper/figures/fig_pareto_accuracy_vs_solvetime.py",
        "scripts/paper/figures/fig_synth_sweep_combined.py",
        "scripts/paper/figures/fig_synth_gap_distribution.py",
        "scripts/paper/figures/fig_synth_gap_direction.py",
        "scripts/paper/figures/fig_synth_gap_decomp.py",
        "scripts/paper/figures/fig_demand_per_node.py",
        "scripts/paper/figures/fig_cost_extended.py",
        "scripts/paper/figures/fig_cost_topology.py",
        "scripts/paper/figures/fig_cost_waterfall.py",
        "scripts/paper/figures/fig_dispatch_heatmap.py",
        "scripts/paper/figures/fig_utils.py",
        "scripts/paper/figures/run_all_figures.py",
    ]
    for path in changed_files:
        lines.append(f"- `{path}`")
    lines.append("- No result CSV, solver output, model output, data source, paper text, Figure 1, or Figure 2 file was modified by this runner.")
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    results: list[dict[str, object]] = []

    for spec in FIGURE_SCRIPTS:
        mod_name = str(spec["module"])
        stem = str(spec["stem"])
        started_at = time.time()
        message = ""
        try:
            mod = importlib.import_module(mod_name)
            mod.main()
            outputs = _fresh_outputs(stem, started_at)
            status = "exported" if outputs else "skipped"
            if not outputs:
                missing = _missing_required_paths(spec)
                if missing:
                    message = "Missing required input file(s): " + ", ".join(missing)
                else:
                    message = "No fresh output files were written; input data may be unavailable."
            print(f"[{status.upper()}] {mod_name.split('.')[-1]}")
        except Exception as exc:
            outputs = []
            status = "failed"
            message = str(exc)
            print(f"[ERR] {mod_name.split('.')[-1]}: {exc}")

        results.append({
            "module": mod_name,
            "stem": stem,
            "inputs": spec["inputs"],
            "status": status,
            "outputs": [str(path) for path in outputs],
            "message": message,
        })

    _write_report(results)
    print(f"[REPORT] {FIG_DIR / 'figure_polish_report.md'}")


if __name__ == "__main__":
    main()
